# Generated by Django 4.2.4 on 2023-08-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='isCompleted',
            new_name='is_completed',
        ),
    ]
